# Generated by Django 4.0.2 on 2022-02-18 08:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None)),
                ('language',
                 models.CharField(choices=[('Chinese',
                                            'Chinese'),
                                           ('English',
                                            'English'),
                                           ('Spanish',
                                            'Spanish'),
                                           ('Arabic',
                                            'Arabic'),
                                           ('French',
                                            'French'),
                                           ('Persian',
                                            'Persian'),
                                           ('German',
                                            'German'),
                                           ('Russian',
                                            'Russian'),
                                           ('Malay',
                                            'Malay'),
                                           ('Portuguese',
                                            'Portuguese'),
                                           ('Italian',
                                            'Italian'),
                                           ('Turkish',
                                            'Turkish'),
                                           ('Lahnda',
                                            'Lahnda'),
                                           ('Urdu',
                                            'Urdu'),
                                           ('Korean',
                                            'Korean'),
                                           ('Hindi',
                                            'Hindi'),
                                           ('Japanese',
                                            'Japanese')],
                                  max_length=30)),
                ('currency',
                 models.CharField(choices=[('USD',
                                            'USD'),
                                           ('EUR',
                                            'EUR'),
                                           ('JPY',
                                            'JPY'),
                                           ('GBP',
                                            'GBP'),
                                           ('AUD',
                                            'AUD'),
                                           ('CAD',
                                            'CAD'),
                                           ('CHF',
                                            'CHF'),
                                           ('CNH',
                                            'CNH'),
                                           ('HKD',
                                            'HKD'),
                                           ('NZD',
                                            'NZD')],
                                  default='USD',
                                  max_length=5)),
            ],
        ),
    ]
